In [1]:
from IPython.core.display import HTML
HTML("""
<style>

div.cell { /* Tunes the space between cells */
margin-top:1em;
margin-bottom:1em;
}

div.text_cell_render h1 { /* Main titles bigger, centered */
font-size: 2.2em;
line-height:1.4em;
text-align:center;
}

div.text_cell_render h2 { /*  Parts names nearer from text */
margin-bottom: -0.4em;
}


div.text_cell_render { /* Customize text cells */
font-family: 'Times New Roman';
font-size:1.5em;
line-height:1.4em;
padding-left:3em;
padding-right:3em;
}
</style>
""")

# PYTHON

<img src='img/1.jpeg'/>

* Мощный гибкий открытый язык
* Простой в изучении
* Простой в использовании
* Общеупотребительный
* Библиотеки для обработки и анализа данных.
* Широчайший спектр применений - от утилит администрирования сети до физических экспериментов, которые привели к подтверждению существования Бозона Хиггса.
* Внутренняя инфраструктура Google, Youtube, Sony Dreamworks, Disney

Популярность(с сайта [githut.info](http://githut.info/)):

   <img src='img/python_popularity.png'/>

# IPython/Jupyter Notebook

*Вы сейчас на него смотрите*

Web-приложение, которое позволяет совмещать в одном документе:
* исполняемый код
* формулы
* пояснения текстом
* виджеты

Состав приложения:
1. Ядро
2. Веб-сервер
3. Приложение

<img src='img/jupyter_diagram.png'/>

NB! Сервер и ядро могут работать на удаленной машине.

Документ состоит из ячеек.
Этот текст находится в markdown ячейке.

### Заголовок - ставим в начале строки несколько символов $#$

1. Списки с цифрами


* и с точками


Формулы в формате LaTeX:

```
$$ P(A \mid B) = \frac{P(B \mid A) \, P(A)}{P(B)} $$
```

$$ P(A \mid B) = \frac{P(B \mid A) \, P(A)}{P(B)} $$


```
Три апострофа для форматирования текста
```

* И html


In [2]:
# Ячейка с кодом
1 + 2

3

## **Магии**  
Дополнительные команды для управления работой ноутбука.

Например, консольная команда текущей директории:

In [3]:
%pwd

'/home/spiralis/git/mlworkshop39_042017/0_python_intro'

! - способ исполнить что-нибудь в консоли.

In [4]:
!pwd

/home/spiralis/git/mlworkshop39_042017/0_python_intro


In [5]:
!ls

img  README.md	Инструменты ML.ipynb


Работающие у вас сейчас маджики:

In [6]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%perl  %%prun  %%pypy  %%python  %%python2  %%python3

Справка python:

In [7]:
?str.replace()

Маджик для учета времени выполнения ячейки:

In [8]:
%%time
import time
for _ in range(1000):
    time.sleep(0.01)

CPU times: user 19.8 ms, sys: 12.9 ms, total: 32.7 ms
Wall time: 10.1 s


# NUMPY

**Рахат-лукум многомерных массивов.**  
Когда обычных списков в Python не хватает. numpy - это одна из основных библиотек Python для вычислений, которая встречается повсюду.

Подключаем библиотеку:

In [10]:
import numpy as np

**Массивы**  
Массив в numpy - таблица со значениями одинакового типа, индексируемая кортежами неотрицательных чисел. Количество измерений в индексе - ранг массива, форма массива(shape) - кортеж, описывающий размер массива по каждому измерению.

Одномерный массив:

In [30]:
a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [37]:
b = np.arange(1, 5, .5)
print(b)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5]


In [38]:
np.linspace(-5,5, 100)

array([-5.        , -4.8989899 , -4.7979798 , -4.6969697 , -4.5959596 ,
       -4.49494949, -4.39393939, -4.29292929, -4.19191919, -4.09090909,
       -3.98989899, -3.88888889, -3.78787879, -3.68686869, -3.58585859,
       -3.48484848, -3.38383838, -3.28282828, -3.18181818, -3.08080808,
       -2.97979798, -2.87878788, -2.77777778, -2.67676768, -2.57575758,
       -2.47474747, -2.37373737, -2.27272727, -2.17171717, -2.07070707,
       -1.96969697, -1.86868687, -1.76767677, -1.66666667, -1.56565657,
       -1.46464646, -1.36363636, -1.26262626, -1.16161616, -1.06060606,
       -0.95959596, -0.85858586, -0.75757576, -0.65656566, -0.55555556,
       -0.45454545, -0.35353535, -0.25252525, -0.15151515, -0.05050505,
        0.05050505,  0.15151515,  0.25252525,  0.35353535,  0.45454545,
        0.55555556,  0.65656566,  0.75757576,  0.85858586,  0.95959596,
        1.06060606,  1.16161616,  1.26262626,  1.36363636,  1.46464646,
        1.56565657,  1.66666667,  1.76767677,  1.86868687,  1.96

In [33]:
a.dtype

dtype('int64')

In [34]:
a.shape

(3,)

In [36]:
b.size

8

In [13]:
print(a)

[1 2 3]


In [14]:
print (a[0], a[2])

1 3


Двумерный массив:

In [15]:
b = np.array([[1,2,3],[4,5,6]])

In [16]:
print(b)

[[1 2 3]
 [4 5 6]]


In [17]:
print(b.shape)

(2, 3)


In [18]:
print(b[0][1])

2


In [19]:
print(b[1][2])

6


###### Всякие функции для создания массива:

*Массив из нулей*

In [20]:
a = np.zeros((3,4))
print(a)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


*Массив из единиц*

In [21]:
b = np.ones((1,2))
print(b)

[[ 1.  1.]]


*Массив, заполненный определенным значением*

In [22]:
c =np.full((3,3),7)
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


*Единичная матрица*

In [23]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

###### *Случайные данные*

Генераторы случайных чисел лежат в ```np.random```. 
Несколько десятков генераторов под [разные распределения](https://docs.scipy.org/doc/numpy/reference/routines.random.html) и еще всякие удобные функции.

Равномерное распределение:

In [43]:
np.random.random((2,2))

array([[ 0.32424891,  0.23563121],
       [ 0.19274211,  0.59151312]])

In [67]:
np.random.normal(loc=4, scale=2, size=((2,2)))

array([[ 4.14145828,  3.33159957],
       [ 5.74778761,  4.20714789]])

In [71]:
np.random.poisson(size=10)

array([3, 0, 2, 1, 1, 2, 0, 0, 0, 1])

...

Перемешивание выборок:

In [72]:
x = np.arange(0, 20)
print(x)
np.random.shuffle(x)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 6  4 10  1 14  5  3 11 18  8  9 13 16 12 19  2  0 15 17  7]


Фиксирование результатов работы random:

In [64]:
np.random.seed(7)

###### Индексация массивов

Есть несколько способов обращения к элементам массивов:

In [73]:
a = np.arange(1,13).reshape((3,4))

print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


* Можно пользоваться обычной адресацией

In [75]:
a[0]

array([1, 2, 3, 4])

In [77]:
a[1,1]

6

In [78]:
a[2][2]

11

* Можно пользоваться слайсингом.

In [26]:
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


* Можно пользоваться обычной адресацией и смешивать её со слайсингом

In [27]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Обращение к строкам:

In [28]:
row_r1 = a[1, :]    
row_r2 = a[1:2, :]  
print (row_r1, row_r1.shape)
print (row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


И к столбцам:

In [82]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)
print (col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [87]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

Последний элемент массива:

In [90]:
A[-1]

array([40, 41, 42, 43, 44])

Выбор "полосками":

In [92]:
A[::2,::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

Индексы отдельным массивом:

In [95]:
row_idx = [1,2,3]
A[row_idx]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [98]:
col_idx = [1,2,-1]
A[row_idx,col_idx]

array([11, 22, 34])

In [105]:
B = np.arange(0,5)
B

array([0, 1, 2, 3, 4])

Бинарные маски:

In [100]:
row_mask = [True, False,True,False,False]
B[row_mask]

array([0, 2])

In [102]:
x = np.arange(0,10,0.5)
x

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [103]:
mask = (5 < x) * (x < 7.5)
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False], dtype=bool)

In [106]:
x[mask]

array([ 5.5,  6. ,  6.5,  7. ])

### Манипуляции с размером массивов

In [144]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [145]:
n,m = A.shape

In [146]:
B = A.reshape((1,n*m))
B

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
        32, 33, 34, 40, 41, 42, 43, 44]])

In [147]:
B = A.flatten()
B

array([ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
       32, 33, 34, 40, 41, 42, 43, 44])

Добавление нового измерения - это просто:

In [148]:
v = np.array([1,2,3])
v.shape

(3,)

In [150]:
v[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [154]:
v[np.newaxis, :]

array([[1, 2, 3]])

Объединить два массива - тоже не проблема:

In [157]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

In [158]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [159]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])


```hstack/vstack```

In [160]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [162]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

### Линейная алгебра

In [114]:
v1 = np.arange(0,5)

$$ \vec{v} * \alpha $$

In [116]:
v1*5

array([ 0,  5, 10, 15, 20])

$$ \vec{v} + \alpha $$

In [118]:
v1+2

array([2, 3, 4, 5, 6])

#### Поэлементные операции:

In [120]:
A*A

array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

In [122]:
v1*v1

array([ 0,  1,  4,  9, 16])

In [127]:
A*v1

array([[  0,   1,   4,   9,  16],
       [  0,  11,  24,  39,  56],
       [  0,  21,  44,  69,  96],
       [  0,  31,  64,  99, 136],
       [  0,  41,  84, 129, 176]])

#### Матричная алгебра:

<img src='img/matmul.svg'/>

In [135]:
np.dot(A,A)

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

In [133]:
np.dot(A,v1)

array([ 30, 130, 230, 330, 430])

In [134]:
np.dot(v1,v1)

30

Тип matrix - матричные операции по умолчанию:

In [137]:
M = np.matrix(A)
v = np.matrix(v1).T

In [139]:
v

matrix([[0],
        [1],
        [2],
        [3],
        [4]])

In [141]:
M*M

matrix([[ 300,  310,  320,  330,  340],
        [1300, 1360, 1420, 1480, 1540],
        [2300, 2410, 2520, 2630, 2740],
        [3300, 3460, 3620, 3780, 3940],
        [4300, 4510, 4720, 4930, 5140]])

In [143]:
M*v

matrix([[ 30],
        [130],
        [230],
        [330],
        [430]])

В numpy очень много математических функций. Обычно их можно применять как методы массивов или же как самостоятельные функции из numpy. Обычно стоит только погуглить - нужная функция будет в первой же ссылке на stackoverflow

In [177]:
print(a)

[[1 2]
 [3 4]]


In [178]:
print(a.sum())

10


In [179]:
print(a.sum(axis=1))

[3 7]


In [180]:
print(a.mean())

2.5


In [181]:
print(a.mean(axis=0))

[ 2.  3.]


In [182]:
print(a.std())

1.11803398875


# SCIPY
**и разреженные матрицы**

Scipy - другая часть numpy, которая разрабатывалась теми же людьми.
В отличие от numpy содержит в основном разнообразные математические функции, которые оперируют в основном оперируют массивами из numpy.
С помщью scipy можно:
* находить интегралы и решать несложные дифференциальные уравнения
* интерполировать
* решать системы линейных уравнений
* выполнять преобразование Фурье
* решать задачи оптимизации
* etc

Нас в этом пакете интересуют разреженные матрицы(sparse matrices).

Что такое разреженная матрица и зачем она может понадобиться?


Представим себе крупную матрицу, в которой лишь очень небольшое несколько элементов отличны от нуля.

<img src='img/sparse_example.JPG'/>

Такие матрицы обычно встречаются в очень больших системах(а язык - это большая система), которые можно описать в матричной форме. В scipy есть хорошая поддержка таких матриц и она настолько хороша, что разреженные матрицы из scipy поддерживаются и в других библиотеках.

Существует несколько форматов разреженных матриц:
* CSR/CSC -ужатые строчки/столбцы
* LIL  - список списков
* COO - координатная форма  
и довольно много других.

Для этих форматов существуют отдельные реализации основных операций, но сами форматы не так очевидны по сравнению с обычными матрицами.

In [184]:
import scipy
import scipy.sparse

##### COO
[документация](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.html#scipy.sparse.coo_matrix)   
Формат содержит список значений (строка, столбец, значение)

Плюсы:
+ самая быстрая конвертация из/в другие форматы
+ не заметит дублей в данных

Минусы:  
- нет поддержки арифметических операций
- нет поддержки слайсинга

Формат предназначен для быстрого создания разреженной матрицы. Как только матрица создана, следует перевод в CSR/CSC форматы для проведения операций.

In [190]:
row  = np.array([0, 0, 1, 3, 1, 0, 0])
col  = np.array([0, 2, 1, 3, 1, 0, 0])
data = np.array([1, 1, 1, 1, 1, 1, 1])
scipy.sparse.coo_matrix((data, (row, col)), shape=(4, 4)).toarray()

array([[3, 0, 1, 0],
       [0, 2, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1]])

##### CSR/CSC  
[документация](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html#scipy.sparse.csr_matrix)
Сжатые строки/столбцы в виде трех списков:
* indptr - содержит в себе кумуллятивную сумму количества элементов в строках матрицы - дословно, $indptr_i = indptr_{i-1} + \sum^{m}_{i=1}[M_{ij}] $
* data - размером в количество ненулевых элементов матрицы, содержит эти элементы, ```data[indptr[i]:indptr[i+1]]```
* indices - строчные индексы для данных из первого списка, ```indices[indptr[i]:indptr[i+1]]```

In [195]:
indptr = np.array([0, 2, 3, 6])
indices = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
scipy.sparse.csr_matrix((data, indices, indptr), shape=(3, 3)).toarray()

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]])

ту же матрицу можно определить иначе:

In [197]:
row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
scipy.sparse.csr_matrix((data, (row, col)), shape=(3, 3)).toarray()

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]], dtype=int64)

Пример того, как построить разреженную матрицу слово-документ, в которой для каждого слова будет подсчитано, сколько раз оно встречается в предложении:

In [196]:
docs = [["hello", "world", "hello"], ["goodbye", "cruel", "world"]]
indptr = [0]
indices = []
data = []
vocabulary = {}
for d in docs:
    for term in d:
        index = vocabulary.setdefault(term, len(vocabulary))
        indices.append(index)
        data.append(1)
    indptr.append(len(indices))
scipy.sparse.csr_matrix((data, indices, indptr), dtype=int).toarray()

array([[2, 1, 0, 0],
       [0, 1, 1, 1]])

CSC - это почти то же самое. Вместо кодирования индексов внутри строки кодируются индексы в столбцах.

Плюсы:
+ Очень эффективные операциии сложения и перемножения в пределах своего типа
+ Быстрый слайсинг  

Минусы:
- медленный слайсинг по "не своей" оси
- очень неудобно менять форму матрицы

Методы перехода между типами данных начинаются на to...

In [199]:
scipy.sparse.csr_matrix((data, indices, indptr), dtype=int).toarray()

array([[4, 2, 0, 0],
       [0, 6, 4, 5]])

In [201]:
scipy.sparse.csr_matrix((data, indices, indptr), dtype=int).tocsc()

<2x4 sparse matrix of type '<class 'numpy.int64'>'
	with 6 stored elements in Compressed Sparse Column format>

In [202]:
scipy.sparse.csr_matrix((data, indices, indptr), dtype=int).tocoo()

<2x4 sparse matrix of type '<class 'numpy.int64'>'
	with 6 stored elements in COOrdinate format>

# PANDAS

<img src='img/pandas.jpg' width=50%/>

Это практически Excel.  
Основными структурами данных в Pandas являются классы Series и DataFrame.  
* Series одномерный индексированный массив данных некоторого фиксированного типа. 
* DataFrame - двухмерная структура данных, представляющая собой таблицу, каждый столбец которой содержит данные одного типа. 

О DataFrame можно думать как о словаре объектов типа Series. Структура DataFrame отлично подходит для представления реальных данных: строки соответствуют признаковым описаниям отдельных объектов, а столбцы соответствуют признакам.

Где-то внутри объектов pandas скрываются массивы из numpy.

In [206]:
import pandas as pd

Создание объекта типа Series. Может работать и как словарь с доступом по индексу, так и список данных.

In [207]:
s = pd.Series([1,3,5,np.nan, 6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

Создание фрейма(аналог листа Excel) с временем в индексе и названиями столбцов:

In [208]:
dates = pd.date_range('20160101', periods=12)
dates

DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
               '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12'],
              dtype='datetime64[ns]', freq='D')

In [212]:
df= pd.DataFrame(np.random.randn(12,4), index=dates, columns=list('ABCD'))
df

A         B         C         D
2016-01-01 -0.090981  0.954115 -0.940279 -0.131276
2016-01-02  0.961076  0.560777 -1.324641  0.665204
2016-01-03 -0.478418  0.385387  0.300680  1.219319
2016-01-04  0.116560 -1.853806 -1.369860  0.731154
2016-01-05 -0.258316  1.137979  0.273439 -0.749066
2016-01-06  1.082407 -0.807398 -2.052636  2.063796
2016-01-07 -1.910749  0.636413  0.938852  0.147066
2016-01-08 -1.683397  1.015015 -1.441544 -1.343629
2016-01-09 -0.361668  0.788505  0.300114  0.810768
2016-01-10 -0.443644 -0.172183 -1.137137 -0.316865
2016-01-11  0.593128 -0.299828  0.475460 -0.573274
2016-01-12 -0.592392  0.039169 -0.194882  0.592385

Загрузка фрейма из файла. Вообще, pandas поддерживает огромное количество источников - может копировать из буфера обмена, читать из текстовых файлов, скачивать по url, запрашивать у баз данных.

In [213]:
data = pd.read_csv('sample.csv')

Набор данных в примере исключительно учебный - прогнозирование риска невозврата кредита.

In [215]:
data.head()

checking_status  duration                  credit_history  \
0     no checking        24                   existing paid   
1        0<=X<200        36              delayed previously   
2     no checking        24                   existing paid   
3     no checking        24                   existing paid   
4              <0        12  critical/other existing credit   

               purpose  credit_amount    savings_status  employment  \
0             used car           5433  no known savings  unemployed   
1              new car           8086        100<=X<500         >=7   
2             radio/tv           1376       500<=X<1000      4<=X<7   
3  furniture/equipment           2835       500<=X<1000         >=7   
4              new car           2171              <100      1<=X<4   

   installment_commitment     personal_status other_parties  ...   \
0                       2  female div/dep/mar          none  ...    
1                       2         male single          none  ...    
2                       4  female div/dep/mar          none  ...    
3                       3         male single          none  ...    
4                       4         male single          none  ...    

   property_magnitude age  other_payment_plans housing existing_credits  \
0      life insurance  26                 none    rent                1   
1                 car  42                 none     own                4   
2                 car  28                 none     own                1   
3      life insurance  53                 none     own                1   
4      life insurance  38                 bank     own                2   

                         job num_dependents  own_telephone foreign_worker  \
0  high qualif/self emp/mgmt              1            yes            yes   
1  high qualif/self emp/mgmt              1            yes            yes   
2                    skilled              1           none            yes   
3                    skilled              1           none            yes   
4         unskilled resident              1           none             no   

  class  
0  good  
1   bad  
2  good  
3  good  
4  good  

[5 rows x 21 columns]

In [216]:
data.describe()

duration  credit_amount  installment_commitment  residence_since  \
count  1000.000000    1000.000000             1000.000000      1000.000000   
mean     20.903000    3271.258000                2.973000         2.845000   
std      12.058814    2822.736876                1.118715         1.103718   
min       4.000000     250.000000                1.000000         1.000000   
25%      12.000000    1365.500000                2.000000         2.000000   
50%      18.000000    2319.500000                3.000000         3.000000   
75%      24.000000    3972.250000                4.000000         4.000000   
max      72.000000   18424.000000                4.000000         4.000000   

               age  existing_credits  num_dependents  
count  1000.000000       1000.000000     1000.000000  
mean     35.546000          1.407000        1.155000  
std      11.375469          0.577654        0.362086  
min      19.000000          1.000000        1.000000  
25%      27.000000          1.000000        1.000000  
50%      33.000000          1.000000        1.000000  
75%      42.000000          2.000000        1.000000  
max      75.000000          4.000000        2.000000

In [218]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
checking_status           1000 non-null object
duration                  1000 non-null int64
credit_history            1000 non-null object
purpose                   1000 non-null object
credit_amount             1000 non-null int64
savings_status            1000 non-null object
employment                1000 non-null object
installment_commitment    1000 non-null int64
personal_status           1000 non-null object
other_parties             1000 non-null object
residence_since           1000 non-null int64
property_magnitude        1000 non-null object
age                       1000 non-null int64
other_payment_plans       1000 non-null object
housing                   1000 non-null object
existing_credits          1000 non-null int64
job                       1000 non-null object
num_dependents            1000 non-null int64
own_telephone             1000 non-null object
foreign_

In [220]:
df.shape

(12, 4)

# Matplotlib и Seaborn

In [ ]:
import matplotlib
%matplotlib inline 

In [ ]:
import seaborn as sns